name: CoolGear
favicon: null
layout_spectrum: 0.58252467145212
typography_spectrum: 0.9851191791240126
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6470742407254875
  lightness: 0.8387045420240611
  saturation: 0.9271369827911258
  rhythmicContrast: 0.27687254664488137
purpose: []
